version: "3.9"
services:
  app:
    restart: always
    build: .
    command: [ "uvicorn","main:app","--host","0.0.0.0","--port","8000" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - pg_data:/data/db

volumes:
  pg_data:
    driver: local