version: "3.9"
services:
  app:
    build: .
    command: [ "uvicorn","main:app","--host","0.0.0.0","--port","8000" ]
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "6000:27017"
    volumes:
      - pg_data:/data/db

volumes:
  pg_data:
    driver: local